AWSTemplateFormatVersion: '2010-09-09'
Description: Create a role for us to later assume and a resource we will have access to in the role
Parameters:
  BucketName:
    Type: String
    Default: "ethereal-sts-fun"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: 
              AWS: "arn:aws:iam::169634835787:user/sts-machine-user"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: 's3:*'
                Resource: [
                  !Sub "arn:aws:s3:::*",
                  !Sub "arn:aws:s3:::${BucketName}",
                  !Sub "arn:aws:s3:::${BucketName}/*"
                ]
