
AWSTemplateFormatVersion: "2010-09-09"
Description: "Building Something"
Resources:
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-iam-user.html
  MyUser:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
      Policies: 
        - PolicyName: MyCoolPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
                - Sid: IamListAccess
                  Effect: Allow
                  Action:
                  - 'iam:ListRoles'
                  - 'iam:ListUsers'
                  Resource: '*'
      UserName: 'my-cfn-user'
  MyInlinePolicy: # Not sure why AWS::IAM::Policy and AWS::IAM::UserPolicy both create customer inline policies but here we are!
    # https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-iam-policy.html
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: MyInlinePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 'ec2:*'
            Resource: '*'
      Users:
        - !Ref MyUser
  MySecondInlinePolicy:
    Type: 'AWS::IAM::UserPolicy'
    Properties:
      PolicyName: MySecondInlinePolicy
      UserName: !Ref MyUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 's3:*'
            Resource: '*'