#!/usr/bin/env bash

set -e

# Create vpc
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region ca-central-1 \
--tag-specifications 'ResourceType=vpc,Tags=[{Key=Name,Value=ethereal-vpc-1}]' \
--query Vpc.VpcId \
--output text)

echo "VPC_ID = $VPC_ID"

#Turn on DNS hostnames
aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames "{\"Value\":true}"
# Create igw
IGW_ID=$(aws ec2 create-internet-gateway \
--tag-specifications 'ResourceType=internet-gateway,Tags=[{Key=Name,Value=ethereal-igw-1}]' \
--query InternetGateway.InternetGatewayId \
--output text)

echo "IGW_ID = $IGW_ID"
# attach igw
aws ec2 attach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID
# create subnet
SUBNET_ID=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--tag-specifications 'ResourceType=subnet,Tags=[{Key=Name,Value=ethereal-subnet-1}]' \
--cidr-block 172.1.0.0/20 \
--query Subnet.SubnetId \
--output text)

echo "SUBNET_ID =  $SUBNET_ID"

# Auto-assign IPv4
aws ec2 modify-subnet-attribute --subnet-id $SUBNET_ID --map-public-ip-on-launch

RT_ID=$(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" \
--query "RouteTables[].RouteTableId[]" \
--output text)

echo "RT_ID = $RT_ID"
# explicitly associate subnet
RT_ASS_ID=$(aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID \
--query AssociationId \
--output text)
echo "RT_ASS_ID = $RT_ASS_ID"
# add route to igw

aws ec2 create-route \
--route-table-id $RT_ID \
--destination-cidr-block 0.0.0.0/0 \
--gateway-id $IGW_ID

# print out delete command because I'm lazy
echo  "./deletevpc $VPC_ID $IGW_ID $SUBNET_ID $RT_ASS_ID $RT_ID"