#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
  echo "No VPC_ID Provided"
else
  export VPC_ID="$1"
fi

if [ -z "$2" ]; then
  echo "No IGW_ID Provided"
else
  export IGW_ID="$2"
fi


if [ -z "$3" ]; then
  echo "No IGW_ID Provided"
else
  export SUBNET_ID="$3"
fi


if [ -z "$4" ]; then
  echo "No IGW_ID Provided"
else
  export RT_ASS_ID="$4"
fi


if [ -z "$5" ]; then
  echo "No IGW_ID Provided"
else
  export RT_ID="$5"
fi

aws ec2 delete-route \
  --route-table-id $RT_ID \
  --destination-cidr-block 0.0.0.0/0

aws ec2 disassociate-route-table --association-id $RT_ASS_ID

aws ec2 delete-subnet --subnet-id $SUBNET_ID

aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

aws ec2 delete-vpc --vpc-id $VPC_ID