AWSTemplateFormatVersion: "2010-09-09"
Description: EC2 instance creation for use with testing nacl and vpcs
Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
  ImageId:
    Type: "AWS::EC2::Image::Id"
    Default: ami-0abac8735a38475db
  SubnetId:
    Type: "AWS::EC2::Subnet::Id"
    Default: subnet-033a5824a8ed3456e
  VPCId:
    Type: "AWS::EC2::VPC::Id"
    Default: vpc-00253ca8e15bba403
  SecurityGroupId:
    Type: "AWS::EC2::SecurityGroup::Id"
    Default: sg-0bd29e4ed9eb4b479
Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
  Ec2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref IamRole
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId:  !Ref ImageId
      IamInstanceProfile: !Ref Ec2InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          SubnetId: !Ref SubnetId
          AssociatePublicIpAddress: true
          GroupSet:
            - !Ref SecurityGroupId
          DeleteOnTermination: true
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo apt-get install lsb-release curl gpg
          curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
          sudo chmod 644 /usr/share/keyrings/redis-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
          sudo apt-get update
          sudo apt-get install -y redis-tools
#"...install -y redis" worked but I think we only need the tools, not the server.