#!/usr/bin/env bash

echo "== deploy rds"

STACK_NAME="rds-basic"

aws cloudformation deploy \
--template-file template.yaml \
--capabilities CAPABILITY_NAMED_IAM \
--no-execute-changeset \
--region ca-central-1 \
--stack-name $STACK_NAME \
--parameter-overrides VpcId="vpc-00253ca8e15bba403" WebServerSGGroupId="sg-0bd29e4ed9eb4b479" RdsSecretArn="arn:aws:secretsmanager:ca-central-1:169634835787:secret:MyRdsPassword-XgVLWm" Username="ethereal" Subnets="subnet-033a5824a8ed3456e,subnet-05e283d35eec28a6f,subnet-0f3d908b1b626ecaa"

