#!/usr/bin/env bash

echo "== create bucket"

if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg ./create-bucket my-bucket-name."
  exit 1
fi
BUCKET_NAME=$1
#https://docs.aws.amazon.com/cli/latest/reference/s3api/create-bucket.html#examples

aws s3api create-bucket --bucket $BUCKET_NAME \
--region ca-central-1 \
--create-bucket-configuration="LocationConstraint=ca-central-1" \
--query Location \
--output text