#!/usr/bin/env bash
echo "== delete objects"

#check for bucket name
if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg ./sync my-bucket-name."
  exit 1
fi

OUTPUT_JSON="./delete_objects.json"

BUCKET_NAME=$1
aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > $OUTPUT_JSON


#| jq -r '.Contents[].Key' \

aws s3api delete-objects --bucket $BUCKET_NAME --delete file://"$OUTPUT_JSON"
