#!/usr/bin/env bash

echo "== sync"

#exit immediately if any command returns a non-zero status
set -e

#check for bucket name
if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg ./sync my-bucket-name."
  exit 1
fi

#check for filename prefix
if [ -z "$2" ]; then
  echo "There needs to be a filename prefix eg ./sync my-bucket-name my-filename-prefix"
  exit 1
fi

BUCKET_NAME=$1
FILENAME_PREFIX=$2

# where we'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove folder if it already exists
rm -r $OUTPUT_DIR

# lets create the output folder
mkdir -p "$OUTPUT_DIR"



# Generate a random number between 5 and 10
NUM_FILES=$(( RANDOM % 6 + 5 ))

echo "Creating $NUM_FILES random files..."

for ((i=1; i<=$NUM_FILES; i++)); do
  # Generate a random filename (e.g., file_x3gk2.txt)
  FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"
  
  # Optionally: generate random content (5-20 characters)
  dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
  # Create the file with the random content
  #echo "$CONTENT" > "$FILENAME"

  #echo "Created $FILENAME with content: $CONTENT"
done

ls $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files