AWSTemplateFormatVersion: 2010-09-09
Description: A simple S3 Bucket
#https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html

#https://docs.aws.amazon.com/AWSCloudFormation/latest/TemplateReference/aws-resource-s3-bucket.html
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    # Properties:
    #   BucketName: DOC-EXAMPLE-BUCKET
    # We don't need to supply a bucket name as AWS will generate a random name for us