#!/usr/bin/env bash

#yq -o json policy.yml > policy.json

aws iam create-policy-version \
--policy-arn arn:aws:iam::169634835787:policy/ethereal-test-policy \
--policy-document "$(yq -o json policy.yml)" \
--set-as-default \
--profile aws-iam-testing

